detectors:
  IrresponsibleModule:
    enabled: false

  UncommunicativeModuleName:
    accept:
      - Stashify::AWS::S3
      - Stashify::File::AWS::S3
      - Stashify::Directory::AWS::S3

  UncommunicativeVariableName:
    accept:
      - s3
